### ISSUE TITLE
Call of function sensorShowCFA() does not match parameter definition

### ISSUE THREAD

**Issue by Andreas-Kromke** [ISET/isetcam#24]
1. In file "isetcam/utility/plots/plotSensor.m" these lines

        fullArray = 0;    % Not the full array
        [g, uData] = sensorShowCFA(sensor,fullArray);

    must be changed to (e.g.)

        [g, uData] = sensorShowCFA(sensor);

    and

        fullArray = 1;    % Show the full array
        [g, uData] = sensorShowCFA(sensor,fullArray);

    to (e.g.)

        [g, uData] = sensorShowCFA(sensor);

2. There is a misleading line in "isetcam/sensor/sensorShowCFA.m" that should be removed:

        if ieNotDefined('fullArray'), fullArray = false; end

Note that as a consequence two of the switch cases in the first mentioned file will become identical. Alternatively one might consider reintroducing the removed "fullArray" parameter and leave that file unchanged.

**Comment by wandell** [comment]
Thank you!   Great to have you reading and checking the code.  I made the change in the dev branch, and then merged that and some other changes into master.
