### ISSUE TITLE
Luminance, FOV, Distance is not working

### ISSUE THREAD

**Issue by FengJin2023** [ISET/isetcam#33]
Luminance, FOV. Distance.
I can change the above 3 values, but the image itself does NOT changed.
Could you help with it?

**Comment by wandell** [comment]
No reason for the scene image to change. These are changes to the metadata about the image.  The OI and Sensor data will change.

Brian Wandell
Stein Family Chair
Stanford University
Http://www.stanford.edu/~wandell
________________________________
From: FengJin2023 ***@***.***>
Sent: Thursday, November 23, 2023 9:08:35 AM
To: ISET/isetcam ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ISET/isetcam] Luminance, FOV, Distance is not working (Issue #33)


Luminance, FOV. Distance.
I can change the above 3 values, but the image itself does NOT changed.
Could you help with is it?

**Comment by wandell** [comment]
I should have added that


  1.  the metadata – displayed in the textbox at the upper right of the figure – does change when you edit fov.  For example the height and width change.

  2.  When there is a full depth map of the image, the ‘Distance’ box should not appear.  This is typically the case for scenes rendered using ISET3d.

The consequence of having a different size and spatial sampling resolution play out when you pass the scene through the optics with a specific spatial blur.

I will respond to your other note with a question.

Thanks for these comments.  It is very helpful to have an independent mind looking these things over.

From: Brian A Wandell ***@***.***>
Date: Thursday, November 23, 2023 at 9:15 AM
To: ISET/isetcam ***@***.***>, ISET/isetcam ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [ISET/isetcam] Luminance, FOV, Distance is not working (Issue #33)
No reason for the scene image to change. These are changes to the metadata about the image.  The OI and Sensor data will change.

Brian Wandell
Stein Family Chair
Stanford University
Http://www.stanford.edu/~wandell
________________________________
From: FengJin2023 ***@***.***>
Sent: Thursday, November 23, 2023 9:08:35 AM
To: ISET/isetcam ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ISET/isetcam] Luminance, FOV, Distance is not working (Issue #33)


Luminance, FOV. Distance.
I can change the above 3 values, but the image itself does NOT changed.
Could you help with is it?

**Comment by FengJin2023** [comment]
Thank you for your response.
I understand how to set those parameters.
BTW, initially I thought these parameters will be directly applied in scene app.
It is just my personal opinion. It might be better to add some description or alert while changing these three parameters.
