### ISSUE TITLE
Introduction of L3 in ipCompute.m - Which L3 render method is needed?

### ISSUE THREAD

**Issue by floriancbeck** [ISET/isetcam#4]
Hello,

I wanted to try the L3 functionality by using the _ipSet()_ to append a trained L3 object and executing the _ipCompute()_ with the _pType_ set to _'l3'_. The L3 object was created with the isetL3. 

When I tried to run the _ipCompute()_ an error occurs in line 96:
`[L3xyz,lumIdx,satIdx,clusterIdx] = L3render(L3,sensor,mode);`

The _L3render()_ is not contained in my path and hence the error occurs. Only the constructor  _l3Render()_ is contained due to the use of isetL3. 

Therefore I would like to ask you to which render function the line 96 in _ipCompute()_ is referring to. Is this function also part of any ISET toolbox?

Many thanks in advance and best regards,
Florian

**Comment by wandell** [comment]
Sorry for the long delay.

Do you have the isetL3 repository?  If you would like it, tell me.  It is not open for public sharing at this point, but I do share it regularly with scientists.

Regards,
Brian
