### ISSUE TITLE
Inconsistent OTF size after oiPadDepthMap in oiCompute

### ISSUE THREAD

**Issue by kfeng19** [ISET/isetcam#7]
Please see the following images.
Image 1: the optical image FFT after oiCompute, which is OTF .* sceneFFT
Image 2: the original OTF used in oiCompute
Image 3: the OTF after `oi = oiSet(oi,'depth map',oiPadDepthMap(scene));` , last line in oiCompute.
I'm not sure what oiPadDepthMap does, but it seems the OTF and optical image FFT should be consistent in size even after the oiCompute...
![photonsFFT_after_padDepthMap](https://user-images.githubusercontent.com/8847195/76690907-30a04900-6602-11ea-997f-d1b59e9675a0.png)
![otf_before](https://user-images.githubusercontent.com/8847195/76690909-372ec080-6602-11ea-9ece-1181296d808b.png)
![otf_after_padDepthMap](https://user-images.githubusercontent.com/8847195/76690915-38f88400-6602-11ea-85b4-0bd9a283789f.png)

**Comment by wandell** [comment]
I can look at this some more, but I am not sure I understand what you are saying.

Which images are not the same size?  The intention is to make the depth map in the oi the same size as the oi image itself.  Are you saying that the function fails?

**Comment by kfeng19** [comment]
So if we look at image 1 and image 2, the sizes of the circles are the same, which is what I would expect, because image 2 is the OTF and image 1 is sceneFFT .* OTF.
However, after the oiPadDepthMap(scene), the OTF changes size and becomes image 3, where the circle is now for some reason larger than those in image 1 and image 2.

**Comment by kfeng19** [comment]
I think there's a couple of underlying problems, both show up in dlMTF (called by oiCalculateOTF) when I check the OTF.
First, for some reason the angular cutoff frequency changes before and after applying the oiPadDepthMap. The relevant line is:
`inCutoffFreq = inCutoffFreq *  oiGet(oi,'distancePerDegree','meters');`.
Also, there's a similar issue as the bug reported in #8. On line 71 we have:
`fpDistance = opticsGet(optics,'focalPlaneDistance');`
However the returned fpDistance is not the image distance in my setup, but simply the focal length. The problem arose in both `opticsGet(optics, 'focalPlaneDistance')` and `oiGet(oi,'focal plane distance')`.

**Comment by wandell** [comment]
I merged the pull request from Kai.  This did not cause any inconsistencies in the numerical values that are checked during validation.
